import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { getApiUserId } from '@/lib/auth/session';
import { generatePinCopy, applyTemplate } from '@/lib/pinterest/copy-generator';
import { createServerSupabaseClient } from '@/lib/supabase/server';

const generateSchema = z.object({
  // Either provide quote metadata directly
  quote_text: z.string().min(1).optional(),
  // Accept any string for collection - we'll normalize it later
  collection: z.string().optional().nullable().transform(val => {
    if (!val) return undefined;
    const normalized = val.toLowerCase().trim();
    if (['grounding', 'wholeness', 'growth'].includes(normalized)) {
      return normalized as 'grounding' | 'wholeness' | 'growth';
    }
    return undefined;
  }),
  mood: z.string().optional().nullable().transform(val => val || undefined),
  // Or reference a quote/mockup/asset by ID
  quoteId: z.string().uuid().optional().nullable(),
  mockupId: z.string().uuid().optional().nullable(),
  assetId: z.string().uuid().optional().nullable(),
  // Optionally use a specific template
  templateId: z.string().uuid().optional().nullable(),
  // Product link for templates - accept any string but validate if provided
  product_link: z.string().optional().nullable().transform(val => val || undefined),
});

export async function POST(request: NextRequest) {
  try {
    await getApiUserId();
    const supabase = await createServerSupabaseClient();

    const body = await request.json();
    const data = generateSchema.parse(body);

    let quoteText = data.quote_text;
    let collection = data.collection;
    let mood = data.mood;

    // If quoteId, mockupId, or assetId provided, fetch the metadata
    if (data.quoteId) {
      const { data: quote } = await (supabase as any)
        .from('quotes')
        .select('text, collection, mood')
        .eq('id', data.quoteId)
        .single();

      if (quote) {
        quoteText = quoteText || quote.text;
        collection = collection || quote.collection;
        mood = mood || quote.mood;
      }
    }

    if (data.mockupId) {
      // Mockups have direct quote_id reference
      const { data: mockup } = await (supabase as any)
        .from('mockups')
        .select('quotes(text, collection, mood)')
        .eq('id', data.mockupId)
        .single();

      if (mockup?.quotes) {
        const quote = mockup.quotes;
        quoteText = quoteText || quote.text;
        collection = collection || quote.collection;
        mood = mood || quote.mood;
      }
    }

    if (data.assetId) {
      const { data: asset } = await (supabase as any)
        .from('assets')
        .select('quotes(text, collection, mood)')
        .eq('id', data.assetId)
        .single();

      if (asset?.quotes) {
        const quote = asset.quotes;
        quoteText = quoteText || quote.text;
        collection = collection || quote.collection;
        mood = mood || quote.mood;
      }
    }

    // Ensure we have required data
    if (!quoteText) {
      return NextResponse.json(
        { error: 'Quote text is required. Provide quote_text directly or a valid quoteId/mockupId/assetId.' },
        { status: 400 }
      );
    }

    // If templateId provided, use that template
    if (data.templateId) {
      const { data: template } = await (supabase as any)
        .from('pin_copy_templates')
        .select('title_template, description_template')
        .eq('id', data.templateId)
        .single();

      if (!template) {
        return NextResponse.json({ error: 'Template not found' }, { status: 404 });
      }

      const result = applyTemplate(template, {
        quote: quoteText,
        collection: collection,
        mood: mood,
        product_link: data.product_link,
      });

      // Generate hashtags and alt_text using auto-generator (templates only provide title/description)
      const autoGenerated = generatePinCopy({
        quote_text: quoteText,
        collection: collection || 'grounding',
        mood: mood,
      });

      return NextResponse.json({
        title: result.title,
        description: result.description,
        alt_text: autoGenerated.alt_text,
        hashtags: autoGenerated.hashtags,
        source: 'template',
      });
    }

    // Generate copy using the auto-generator
    const generated = generatePinCopy({
      quote_text: quoteText,
      collection: collection || 'grounding',
      mood: mood,
    });

    return NextResponse.json({
      ...generated,
      source: 'auto-generated',
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: 'Invalid request data', details: error.issues }, { status: 400 });
    }
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    console.error('Error generating copy:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal error' },
      { status: 500 }
    );
  }
}
