// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/supabase.ts
// For now, we provide base types that will be extended

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          global_mode: 'supervised' | 'assisted' | 'autopilot';
          module_overrides: Json;
          transitioning_to: 'supervised' | 'assisted' | 'autopilot' | null;
          transition_started_at: string | null;
          guardrails: Json;
          timezone: string;
          setup_progress: Json;
          setup_completed_at: string | null;
          digest_preferences: Json;
          notification_preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          global_mode?: 'supervised' | 'assisted' | 'autopilot';
          module_overrides?: Json;
          transitioning_to?: 'supervised' | 'assisted' | 'autopilot' | null;
          transition_started_at?: string | null;
          guardrails?: Json;
          timezone?: string;
          setup_progress?: Json;
          setup_completed_at?: string | null;
          digest_preferences?: Json;
          notification_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          global_mode?: 'supervised' | 'assisted' | 'autopilot';
          module_overrides?: Json;
          transitioning_to?: 'supervised' | 'assisted' | 'autopilot' | null;
          transition_started_at?: string | null;
          guardrails?: Json;
          timezone?: string;
          setup_progress?: Json;
          setup_completed_at?: string | null;
          digest_preferences?: Json;
          notification_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      activity_log: {
        Row: {
          id: string;
          user_id: string;
          action_type: string;
          module: string | null;
          details: Json;
          executed: boolean;
          operator_mode: string;
          previous_value: Json | null;
          new_value: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          action_type: string;
          module?: string | null;
          details?: Json;
          executed?: boolean;
          operator_mode: string;
          previous_value?: Json | null;
          new_value?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          action_type?: string;
          module?: string | null;
          details?: Json;
          executed?: boolean;
          operator_mode?: string;
          previous_value?: Json | null;
          new_value?: Json | null;
          created_at?: string;
        };
      };
      approval_items: {
        Row: {
          id: string;
          user_id: string;
          type: 'asset' | 'mockup' | 'pin' | 'ugc' | 'product';
          status: 'pending' | 'approved' | 'rejected' | 'skipped' | 'processing';
          reference_id: string;
          reference_table: string;
          payload: Json;
          confidence_score: number | null;
          flags: string[];
          flag_reasons: Json;
          priority: number;
          processed_at: string | null;
          processed_by: string | null;
          rejection_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'asset' | 'mockup' | 'pin' | 'ugc' | 'product';
          status?: 'pending' | 'approved' | 'rejected' | 'skipped' | 'processing';
          reference_id: string;
          reference_table: string;
          payload: Json;
          confidence_score?: number | null;
          flags?: string[];
          flag_reasons?: Json;
          priority?: number;
          processed_at?: string | null;
          processed_by?: string | null;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'asset' | 'mockup' | 'pin' | 'ugc' | 'product';
          status?: 'pending' | 'approved' | 'rejected' | 'skipped' | 'processing';
          reference_id?: string;
          reference_table?: string;
          payload?: Json;
          confidence_score?: number | null;
          flags?: string[];
          flag_reasons?: Json;
          priority?: number;
          processed_at?: string | null;
          processed_by?: string | null;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
